### ISSUE TITLE
[site] keresőoptimalizálás - meta adatok

### ISSUE THREAD

**Issue by 6uliver** [flowacademyhu/piac-app#238]
- [ ] állítsuk be a honlap nyelvét magyarra, hogy a böngészők, a szövegfelolvasók és a keresőmotorok tudják, hogy magyar nyelvű az oldal (a html lang attribute most "en")
- [ ] állítsuk be a default meta descriptiont erre: "Ahol a kézműves és termelői piacok, az árusok és a vásárlók egymásra találhatnak."
- [ ] állítsuk be a default meta keywords-öt erre: "félpénzzel, kézműves, termelői, piac, piacok, árus, árusok, vásárló, vásárlók"
- [ ] állítsuk be a title-t és a descriptiont a piac listaoldalon: "Félpénzzel - Piacok", "Kézműves és termelői piacok a közeljövőben"
- [ ] állítsuk be a title-t és a descriptiont a piac profiloldalán: például "Félpénzzel - Böba baba-mama vásár", "27 árus - Szálka Halászcsárda és Rendezvényház (Szeged, Közép Kikötő sor 9/A.) - november 21. 09:00 - 14:00"
- [ ] állítsuk be a title-t és a descriptiont az árus listaoldalon: "Félpénzzel - Árusok", "Kézműves árusok és termelők"
- [ ] állítsuk be a title-t és a descriptiont az árus profiloldalán: például "Félpénzzel - JUST IN CASE - craft store", "Praktikus textiltermékek & környezettudatos ajándékcsomagok. Neszeszertől a táskákig - konyhától a fürdőszobáig."

Ajánlott library a dinamikus meta tagekhez: https://www.npmjs.com/package/react-helmet-async)
