### ISSUE TITLE
Árusok listája

### ISSUE THREAD

**Issue by sandorforgo** [flowacademyhu/piac-app#3]
Piacokat kedvelő felhasználóként szeretném látni a mobiltelefonomon a rendszerben elérhető Árusok listáját egy weboldalon.
Az adatbázisban elérhető Árusok listáját a design dokumentáció szerint kell megjeleníteni a következő adatokkal ABC sorrendben: 
Név 
Logo 
Rövid bemutatkozás (maximum 100 karakter) 

- [x] API definíció
 - [x] Entitások felvétele
 - [x] DB tesztadatokkal való feltöltése (a backend szolgáltassa az adatokat)
 - [x] Service-ek implementálása (lekér elemeket a DB-ből)
 - [x] Header
 - [x] Egy kártya kialakítása
- [x]  Adatok a kártyára
- [x] Kártyák listája
