### ISSUE TITLE
Árus profiloldal

### ISSUE THREAD

**Issue by sandorforgo** [flowacademyhu/piac-app#5]
Az árusok listájában (a kettő közül bármelyikben), ha kiválasztom az egyik árust, annak jelenjen meg a profiloldala, melyen legyenek elérhetőek legalább ugyanazok az információk, mint listanézetben, de ezen felül a hosszabb leírás (max 1000 karakter) és a termékeik is.

- [x] Header (név, logo, fizetési adat, rövid leírás) 
- [x] Navigation bar az Info és Piac ikonokkal
- [x] Termékek rész egy String listával
- [x] Elérhetőségek (FB, Instagram, web, email, telefon)
- [x] Hosszú leírás (Bemutatkozás max 1000 karakterben)
