### ISSUE TITLE
Skeleton kialakítása

### ISSUE THREAD

**Issue by taritamas89** [flowacademyhu/piac-app#6]
Project skeleton kialakítása:

- [x] Backend - frontend külön szervezése
- [x] Docker - MySQL kapcsolat kialakítása
- [x] create react app / frontend skeleton bekötése
